# Generated automatically from Makefile.in by configure.
# KDE tags expanded automatically by am_edit - $Revision$ 
# Makefile.in generated automatically by automake 1.4a from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

####### kdevelop will overwrite this part!!! (begin)##########

DISTFILES= 1.bmp 10.bmp 11.bmp 12.bmp 13.bmp 14.bmp 15.bmp 16.bmp \
17.bmp 18.bmp 19.bmp 2.bmp 20.bmp 21.bmp 22.bmp 23.bmp 24.bmp \
25.bmp 26.bmp 27.bmp 28.bmp 29.bmp 3.bmp 30.bmp 31.bmp 32.bmp \
4.bmp \
400000.bmp 400001.bmp 400002.bmp 400003.bmp 400004.bmp 400005.bmp \
400006.bmp 400007.bmp 400008.bmp 400009.bmp 400010.bmp 400011.bmp \
400012.bmp 400013.bmp 400014.bmp 400015.bmp 400016.bmp 400017.bmp \
400018.bmp 400019.bmp 400020.bmp 400021.bmp 400022.bmp 400023.bmp \
400024.bmp \
5.bmp 6.bmp 7.bmp 8.bmp 9.bmp background.bmp \
deck1.bmp deck2.bmp deck3.bmp deck4.bmp \
t1.bmp t2.bmp t3.bmp \
t4.bmp t5.bmp tback.bmp type1.bmp type2.bmp type3.bmp  \
Makefile.am Makefile.in

EXTRA_DIST =lskatpic.taz  

SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /opt/kde2
exec_prefix = ${prefix}

bindir = $(exec_prefix)/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/lskat
pkglibdir = $(libdir)/lskat
pkgincludedir = $(includedir)/lskat

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INSTALL_STRIP_FLAG =
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = @target_alias@
target_triplet = @target@
AS = @AS@
CC = gcc
CPP = gcc -E
CXX = g++
CXXCPP = @CXXCPP@
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/opt/kde2/include
KDE_LDFLAGS = -L/opt/kde2/lib
KDE_RPATH = -rpath $(kde_libraries) -rpath $(qt_libraries) -rpath $(x_libraries)
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
LD = /usr/bin/ld
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBJPEG = @LIBJPEG@
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBSOCKET = 
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool --silent
LIBUCB = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lformula
LIB_KHTML = @LIB_KHTML@
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_MEDIATOOL = -lmediatool
LIB_QT = -lqt $(LIBPNG) -lXext $(LIB_X11) $(X_PRE_LIBS)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/lib/qt2/bin/moc
MSGFMT = /usr/bin/msgfmt
NM = /usr/bin/nm -B
OBJDUMP = @OBJDUMP@
PACKAGE = lskat
PAMINC = @PAMINC@
PAMLIBPATHS = @PAMLIBPATHS@
PAMLIBS = @PAMLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
QT_INCLUDES = -I/usr/lib/qt2/include
QT_LDFLAGS = -L/usr/lib/qt2/lib
RANLIB = ranlib
TOPSUBDIRS = @TOPSUBDIRS@
USER_INCLUDES = 
USER_LDFLAGS = 
USE_NLS = yes
VERSION = 0.9
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS =  -lSM -lICE
all_includes = -I/opt/kde2/include -I/usr/lib/qt2/include  -I/usr/X11R6/include
all_libraries = -L/opt/kde2/lib -L/usr/lib/qt2/lib  -L/usr/X11R6/lib
idldir = @idldir@
kde_appsdir = $(prefix)/share/applnk
kde_bindir = $(exec_prefix)/bin
kde_cgidir = $(exec_prefix)/cgi-bin
kde_confdir = $(prefix)/share/config
kde_datadir = $(prefix)/share/apps
kde_htmldir = $(prefix)/share/doc/HTML
kde_icondir = $(prefix)/share/icons
kde_includes = /opt/kde2/include
kde_libraries = /opt/kde2/lib
kde_locale = $(prefix)/share/locale
kde_mimedir = $(prefix)/share/mimelnk
kde_servicesdir = $(prefix)/share/services
kde_servicetypesdir = $(prefix)/share/servicetypes
kde_sounddir = $(prefix)/share/sounds
kde_toolbardir = $(prefix)/share/toolbar
kde_wallpaperdir = $(prefix)/share/wallpapers
micodir = @micodir@
qt_includes = /usr/lib/qt2/include
qt_libraries = /usr/lib/qt2/lib
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs

all:
	rm -f lskatpic.taz
	tar czf lskatpic.taz *

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = grafix

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu lskat/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

clean:	
	rm lskatpic.taz

distclean:	clean
	rm Makefile

dvi:
	echo Making dvi

check:
	echo check





	echo install in grafix


install:	install-data-local
install-data-am:	install

uninstall:	uninstall-local
	

install-data-local: 	all
#>- 	$(mkinstalldirs) $(kde_datadir)/lskat/
#>+ 1
	$(mkinstalldirs) $(DESTDIR)$(kde_datadir)/lskat/
#>- 	$(INSTALL_DATA) lskatpic.taz $(kde_datadir)/lskat/lskatpic.taz
#>+ 1
	$(INSTALL_DATA) lskatpic.taz $(DESTDIR)$(kde_datadir)/lskat/lskatpic.taz

uninstall-local:
#>- 	-rm -rf $(kde_datadir)/lskat
#>+ 1
	-rm -rf $(DESTDIR)$(kde_datadir)/lskat


































#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps po/Makefile
	cd $(top_srcdir) && perl am_edit lskat-0.9/grafix/Makefile.in


#>+ 2
final:
	$(MAKE) all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean
